module.exports.materialEscolar = [
    {nome: 'Agenda', db: 'agenda'},
    {nome: 'Apontador', db: 'apontador'},
    {nome: 'Borracha', db: 'borracha'},
    {nome: 'Bloco folha de almaço', db: 'bloco folha de almaco'},
    {nome: 'Caderno', db: 'caderno'},
    {nome: 'Caneta esferográfica', db: 'caneta esferografica'},
    {nome: 'Cartolina', db: 'cartolina'},
    {nome: 'Cola branca', db: 'cola branca'},
    {nome: 'Cola bastão', db: 'cola bastao'},
    {nome: 'Compasso', db: 'compasso'},
    {nome: 'Estojo', db: 'estojo'},
    {nome: 'Folha EVA', db: 'folha eva'},
    {nome: 'Giz de cera', db: 'giz de cera'},
    {nome: 'Lápis / Lapiseira', db: 'lapis lapiseira'},
    {nome: 'Lápis de cor (caixa)', db: 'lapis de cor'},
    {nome: 'Livro didático', db: 'livro didatico'},
    {nome: 'Livro paradidático', db: 'livro paradidatico'},
    {nome: 'Marca texto', db: 'marca texto'},
    {nome: 'Massa para modelar', db: 'massa para modelar'},
    {nome: 'Mochila', db: 'mochila'},
    {nome: 'Papel sulfite (pacote)', db: 'papel sulfite'},
    {nome: 'Régua', db: 'regua'},
    {nome: 'Tesoura escolar (sem ponta)', db: 'tesoura escolar'},
    {nome: 'Tinta', db: 'tinta'},
    {nome: 'Tinta guache (caixa)', db: 'tinta guache'},
    {nome: 'Tinta aquarela (caixa)', db: 'tinta aquarela'},
    {nome: 'Outro', db: 'outro'}
];